"""Initial Table

Revision ID: 66c943794707
Revises: 
Create Date: 2020-05-27 23:02:42.723455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c943794707'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    drinks_table = op.create_table('drink',
    sa.Column('id', sa.Integer().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('recipe', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )

    op.bulk_insert(
        drinks_table,
        drinks
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drink')
    # ### end Alembic commands ###

drinks = [
    {"title":"milk","recipe":'[{"name":"milk","color":"white","parts":1}]'},
    {"title":"coffee","recipe":'[{"name":"coffee","color":"black","parts":1}]'},
    {"title":"hot chocolate","recipe":'[{"name":"milk","color":"brown","parts":1},{"name":"chocolate","color":"brown","parts":1}]'},
    {"title":"mocca","recipe":'[{"name":"milk","color":"white","parts":1},{"name":"chocolate","color":"brown","parts":1},{"name":"coffee","color":"black","parts":1}]'}
]
